# Generated by Django 4.1.2 on 2022-12-13 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ask_Chat_Get', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask', to='Ask_Chat_Get.ask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GET', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
