# Generated by Django 4.1.2 on 2022-12-14 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ask_Chat_Get', '0003_ask_image_get_image_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='date',
        ),
        migrations.RemoveField(
            model_name='get',
            name='date',
        ),
        migrations.AddField(
            model_name='ask',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='get',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
