# Generated by Django 4.1.2 on 2022-12-15 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Ask_Chat_Get', '0004_remove_ask_date_remove_get_date_ask_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
