# Generated by Django 4.1.2 on 2022-12-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ask_Chat_Get', '0005_alter_ask_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHAT',
        ),
    ]
