# Generated by Django 4.1.2 on 2022-12-10 09:50

from django.db import migrations, models
import django.utils.timezone
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=post.models.user_directory_path, verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
