# Generated by Django 4.1.2 on 2022-12-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentification', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_pciture'),
        ),
    ]
