# Generated by Django 4.1.2 on 2022-12-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentification', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg',
            field=models.CharField(choices=[('bg1', 'Light'), ('bg2', 'Dim'), ('bg3', 'Dark')], default='bg1', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.IntegerField(choices=[(252, 'purple'), (52, 'yellow'), (352, 'red'), (152, 'green'), (202, 'blue')], default=252),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.CharField(choices=[('f1', 'Size_1'), ('f2', 'Size_2'), ('f3', 'Size_3'), ('f4', 'Size_4'), ('f4', 'Size_5')], default='f2', max_length=7),
        ),
    ]
